package com.tharaka.corebank.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-09-15T04:41:28.328+05:30
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "AccountServicePortService",
                  wsdlLocation = "file:/C:/Users/Tharaka%20Perera/IdeaProjects/bankIntegrator/src/main/resources/wsdl/bankAccountDetailsWsdl.wsdl",
                  targetNamespace = "http://tharaka.com/corebank/model")
public class AccountServicePortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tharaka.com/corebank/model", "AccountServicePortService");
    public final static QName AccountServicePortSoap11 = new QName("http://tharaka.com/corebank/model", "AccountServicePortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Tharaka%20Perera/IdeaProjects/bankIntegrator/src/main/resources/wsdl/bankAccountDetailsWsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountServicePortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Tharaka%20Perera/IdeaProjects/bankIntegrator/src/main/resources/wsdl/bankAccountDetailsWsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountServicePortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServicePortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AccountServicePortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccountServicePortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccountServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AccountServicePort
     */
    @WebEndpoint(name = "AccountServicePortSoap11")
    public AccountServicePort getAccountServicePortSoap11() {
        return super.getPort(AccountServicePortSoap11, AccountServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountServicePort
     */
    @WebEndpoint(name = "AccountServicePortSoap11")
    public AccountServicePort getAccountServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(AccountServicePortSoap11, AccountServicePort.class, features);
    }

}
